services:
  redis:
    image: redis:alpine
    container_name: redis_dev
    ports:
      - "6379:6379"  # Maps [Local Port]:[Container Port]
    volumes:
      - redis_data:/data

volumes:
  redis_data: